language: python
compiler: g++
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
install:
  # C++14
  - sudo apt-get install -qq g++-6 gcc
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install -y libboost-dev
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install cython pytest scipy numpy
  - ./build-module.sh
script:
  - py.test
