language: python
compiler: g++
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
cache: pip
env:
  - BOOST_VERSION="1.65.1" BOOST_ROOT=`pwd`'/geometry/include/boost'
install:
  # C++14
  - sudo apt-get install -qq g++-6 gcc git
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - git clone https://github.com/boostorg/geometry.git
  - cd geometry && git checkout boost-${BOOST_VERSION} && cd ..
  - pip install cython pytest scipy numpy
  - ./build-module.sh
python:
  - "2.7"
  - "3.5"
  - "3.6"
script:
  - py.test
