language: python
compiler: g++
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
cache: pip
env:
  - BOOST_VERSION="1.61.0" BOOST_ROOT=`pwd`'/boost_1_61_0/boost'
install:
  # C++14
  - sudo apt-get install -qq g++-6 gcc git
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - wget https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.gz
  - tar zxvf boost_1_61_0.tar.gz
  - pip install cython pytest scipy numpy
  - ./build-module.sh
python:
  - "2.7"
  - "3.5"
  - "3.6"
script:
  - py.test
