language: python
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo apt-get install -y libboost-dev
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install cython pytest scipy numpy
  - ./build-module.sh
script:
  - py.test
